### ISSUE TITLE
Back-end requirements

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#1]
### Description

Som biolog på Rungstedlund vil jeg gerne have organiseret data over redekasserne i fuglenes ynglesæson, så der senere kan laves databehandling. God data for mig er, at hver observation tilsvarer et kassecheck. Et check af en kasse involverer at kigge i kassen med et kamera og angive dens status.

### Tasks

Data indebærer:

- [ ] Dato
- [ ] Kassenummer
- [ ] Kassestatus

Af forskellige kassestatus er der:

- [ ] Tom
- [ ] Rede
- [ ] Æg (med/uden rugende fugl, antal æg, art)
- [ ] Unger (med/uden rugende fugl, antal, art)
- [ ] Ringmærkede unger (Antal, art, ringnummer)
- [ ] Ude af drift (årsag)

**Comment by asktheo** [comment]
Skal der indkodes et interval til næste kassetjek, hvis ungerne ringmærkes ?

**Comment by philipelbek** [comment]
Ja det skal der. Mejser får 1-2 kuld og det næste kuld er vel i samme kasse og rede. 3 uger er nok et godt interval, da ungerne teknisk set kan flyve fra reden samme dag som de bliver ringmærket, hvorved kassen nu indeholder en rede.

**Comment by asktheo** [comment]
Jeg lukker dette issue og flytter ønsket om felt med "ringmærkede unger" til næste milestone

**Comment by asktheo** [comment]
Jeg lukker dette issue og flytter ønsket om felt med "ringmærkede unger" til næste milestone
