### ISSUE TITLE
Access to online application

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#2]
### Description

Som frivillig i fuglegruppen vil jeg gerne have at det er intuitivt og nemt at lave en indtastning på en kasse, så alle, uanset alder og mærke på smartphone, kan gøre det.

### Tasks

- [ ] Nem adgang til webbaseret applikation (mulighed for en nem genvej)
- [ ] Ingen krav til login
- [ ] Få tydelige knapper
- [ ] Ingen tvivl op flowet på indtastningen

**Comment by asktheo** [comment]
Udviklerteamet har talt om at anbefale login i "Working Product" milestone, som sikkerhed for en vis dataintegritet, men det kan gøres meget nemt ved at brugeren kan skal logge ind første gang i sæsonen og derefter er logget ind hver gang ved åbning. Desuden kan det laves, så der logges ind med Google eller et andet id fra mobiltelefonen. Når brugeren er logget ind gemmes brugernavn på hvert kassecheck. Det kan i stedet laves med en til flere fælles brugere, som er registreret i databasen, men hver "rigtige bruger" vil stadig skulle logge ind med den bruger for at få et access-token (adgangsbevis), og det for hver enhed, som brugeren benytter og for hver browser, der benyttes, da adgangen gemmes i browser-brugerens cache.

**Comment by asktheo** [comment]
Jeg lukker dette og laver et mere specifikt nyt et ang. login.
