### ISSUE TITLE
Submission of nestbox observation

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#3]
### Description

Som frivillig i fuglegruppen vil jeg gerne lave en indtastning af en kasse på min rute. Jeg bruger at lille kamera til at se hvad der er i kassen. På min smartphone kan jeg nu lave en indtastning ved at vælge dato, kassenummer og status for kassen. 

### Tasks

- [ ] Vælg dato (nøjes med at gøre dette en gang for hele turen)
- [ ] Skriv kassenummer (alle kasser skal registreres i systemet på forhånd. Kassen vælges ud fra autofill.)
- [ ] Vælg kassestatus (ved dropdown). 

Muligheder for kassestatus er (med flere valgmuligheder i parentes):

- [ ] Tom (ingen valgmuligheder)
- [ ] Æg (med/uden rugende fugl, antal æg, art)
- [ ] Unger (med/uden rugende fugl, antal, art)
- [ ] Ringmærkede unger (Antal, art, ringnummeinterval).
- [ ] Ude af drift (årsagen til dette).

**Comment by asktheo** [comment]
Kassenummer indtastes ikke, men vælges på forsiden (checklisten).
Lukker denne. Antal af ringmrk. unger overføres til et nyt issue
