### ISSUE TITLE
Nestbox in use, but needs repairs

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#4]
### Description

Som frivillig i fuglegruppen kan jeg nemt finde fejl på redekasserne selvom de er benyttet af en fugl. For at kunne lave reperationer løbende eller efter sæsonen er slut, har jeg brug for at kunne angive at en kasse har brug for reparation, og hvilken type reperation der skal udføres. Jeg skal også kunne se hvilke kasser der har brug for reparation. Hvis jeg foretager en reperation af en kasse, skal det kunne angives at den er repareret. Også uden at foretage en observation af kassen. Dette skal muligvis fungere sideløbende til at lave observationer, så tingene ikke bliver rodet sammen.

### Tasks

- [ ] Angive at kassen har brug for reperation samt hvilken type.
- [ ] Se hvilke kasser der har brug for reperationer og hvilke kommentarer der er noteret.
- [ ] Angive at en kasse er blevet repareret. 
- [ ] Muligvis en ny back-end tabel med kommentarer til kasser.
