### ISSUE TITLE
Overview of nestboxes status

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#5]
### Description

Som både frivillig og ringmærker skal jeg nemt kunne få et overblik over kassernes status. Dette skal kunne tilgåes via webapplikationen som en anden funktion. Jeg skal nemt kunne se hvilke kasser der skal tjekkes i hvilke uger. For eksempel:

På baggrund af tidligere observationer, skal der tjekkes 8 kasser i næste uge: 1 der var tom, 3 som havde rede, 3 der havde æg og 1 der havde unger. 

Når jeg tilføjer en ny observation til ovenstående kasser, ryger de automatisk ned i listen og skal tjekkes igen en senere uge. 

Jeg er nu en ældre frivillig, og kan godt lide at notere i hånden når jeg er ude. Jeg vil derfor gerne kunne printe listen over kasser der skal tjekkes, og notere på denne liste hvad den nye status er. Når jeg kommer hjem taster jeg de nye observationer und. 

### Tasks

- [ ] At kunne tilgå kasseoverblikket i webapplikationen. 
- [ ] At kunne se en liste over kasser der skal tjekkes for hver uge.
- [ ] Hver kasse skal have angivet tidligere status og dato for denne.
- [ ] At kunne printe en oversigt over kasser der skal tjekkes for en given uge, samt kunne angive ny information på dette print til senere indtastning.

**Comment by asktheo** [comment]
Note: kassecheck-dato laves pt. automatisk, så man ikke behøver indtaste den. Det kan dog give udfordringer, hvis den ældre frivillige venter med at taste checket ind.

**Comment by asktheo** [comment]
I forlængelse af min kommentar: Jeg tror, der er brug for et decideret dato-felt, så man kan taste ind senere, uden at det resulterer i en forkert dato.

**Comment by asktheo** [comment]
Vi kigger på at lave en knap, så man kan aktivere et dato felt og skrive datoen ind der.
