### ISSUE TITLE
Timeintervals between nestbox checks

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#7]
### Description

Som administrator af redekasserprojektet vil jeg gerne sørge for, at alle kasserne formår at blive tjekket til tiden, og at alle ungerne får ring på. Jeg skal derfor sørge for, at:

1. jeg har bemanding nok til at nå rundt til kasserne til tiden
2. vi ikke misser den korte periode hvor ungerne kan ringmærkes.

Jeg kan derfor have behov for, at justere på tidsintervallet mellem to check af en kasse. Tidsintervallet mellem checks angiver i hvilken uge, en kasse bliver placeret i kasseoverblikket.

### Tasks

Hvis en kasse       -     check igen om

- [ ] er tom             -     4-6 uger
- [ ] har rede          -     2-3 uger
- [ ] har æg            -     1-2 uger
- [ ] har unger       -     2-3 dage
